name: CI - Run Tests and Linting

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

jobs:
  test-and-lint:
    name: Test code with pytest and check lint with flake8.
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          if [ -f requirements . txt ]; then pip install -r requirements . txt ; fi

      - name: Run pytest
        run: pytest

      - name: Run flake8
        run: flake8 .